/* Request statuses */
const REQUEST_STATUS_IDLE = "idle";
const REQUEST_STATUS_PENDING = "pending";
const REQUEST_STATUS_SUCCESS = "success";
const REQUEST_STATUS_FAILURE = "failure";

export const RequestStatuses = {
  IDLE: REQUEST_STATUS_IDLE, PENDING: REQUEST_STATUS_PENDING, SUCCESS: REQUEST_STATUS_SUCCESS,
  FAILURE: REQUEST_STATUS_FAILURE
};
